name: Scheduled Rebuild

on:
  schedule:
    - cron: "0 15 * * *" # 毎日０：００に実行（JST）
  workflow_dispatch: # 手動実行用

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Build
        run: |
          curl -X POST "${{ secrets.CF_BUILD_HOOK }}"
